a mere two scans

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -37,12 +37,6 @@ jobs:
           npm install eslint@8.10.0
           npm install @microsoft/eslint-formatter-sarif@2.1.7
 
-      - name: Run ESLint to stdout
-        run: npx eslint .
-          --config .eslintrc.js
-          --ext .js,.jsx,.ts,.tsx
-        # continue-on-error: true
-
       - name: Run ESLint to File
         if: success() || failure()
         run: npx eslint .
@@ -50,7 +44,7 @@ jobs:
           --ext .js,.jsx,.ts,.tsx
           --format @microsoft/eslint-formatter-sarif
           --output-file eslint-results.sarif
-        # continue-on-error: true
+        continue-on-error: true
 
       - name: Upload analysis results to GitHub
         uses: github/codeql-action/upload-sarif@v2
@@ -59,13 +53,20 @@ jobs:
           sarif_file: eslint-results.sarif
           wait-for-processing: true
 
-      - name: Fail this Action iff ∃ ESLint findings
-        #if: success() || failure()
+      - name: Run ESLint to stdout
+        # Fail this Action iff ∃ ESLint findings
         run: npx eslint .
           --config .eslintrc.js
           --ext .js,.jsx,.ts,.tsx
-          --format @microsoft/eslint-formatter-sarif
-          --output-file eslint-results.sarif
         continue-on-error: false
+
+      #- name: Fail this Action iff ∃ ESLint findings
+      #  #if: success() || failure()
+      #  run: npx eslint .
+      #    --config .eslintrc.js
+      #    --ext .js,.jsx,.ts,.tsx
+      #    --format @microsoft/eslint-formatter-sarif
+      #    --output-file eslint-results.sarif
+      #  continue-on-error: false
 
 
